### ISSUE TITLE
Import data from a CSV file using the URL doesn't work for tables

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/visualizer#892] opened 2022-04-11 18:16 UTC
### Description:

It seems that there is an issue with the option to import data from URL, from a CSV file, for the tables. I tried to import the data like this a few times from a Google Spreadsheet where I imported a CSV file and every time I get the following error.

![Capture1](https://user-images.githubusercontent.com/86592341/162802321-45ef4ddc-bdc1-4c25-9cbf-9377d26249d3.PNG)

To make sure the data is correctly written in the files I used, I also uploaded a file with it using the "Import data from file" option and that worked as expected.

### How to reproduce:

1. Create a CSV file and import it in a Google Spreadsheet
2. Try to import it in a table using the "Import data from URL / Import from CSV" option
3. Check the error

### Expected behaviour:
The import will be successfully completed and no error will appear.

### Current behaviour:
An error appears and the data can't be imported.

### Reference:

This is one of the spreadsheets I used --> https://docs.google.com/spreadsheets/d/1-1WdNLRVKkTrxMF1f45HR0C_ySYyyS0Ff6YL2eDvDGk/edit?usp=sharing

Here is a thread reporting an issue that may be related to this --> https://wordpress.org/support/topic/latest-versions-of-visualizer-do-not-display-table-with-google-sheets-csv-url/#post-15526362

### Technical info
* WordPress version: 5.9.3
* Plugin version: 3.7.5

**Comment by girishpanchal30** [comment] 2022-04-12 12:58
Hello @MarinescuLucia,
Can you please follow the document steps to import google Sheets data?
Docs: https://docs.themeisle.com/article/607-how-can-i-populate-data-from-google-spreadsheet

I have checked with provided google sheet URL in the document and it's working fine for me.

Thanks

**Comment by Skystream96** [comment] 2022-04-14 09:29
Hello @girishpanchal30 ,

I can confirm that this is indeed an issue as I have also tested on Local and I encountered this error in the Console Log.
<img width="1664" alt="Screenshot 2022-04-14 at 12 08 06" src="https://user-images.githubusercontent.com/82535909/163355227-c525dc37-834c-4e36-a6cb-322cbf71c7e6.png">

I tried using the latest versions of Visualizer on PHP 7.4 to 8.0 and also using the latest version of WP but to no avail. Importing the same file from the computer instead of the URL works fine in my case too. 

The error seems to be coming from the datatables.min.js file in the sort function at line 1537.
<img width="1350" alt="Screenshot 2022-04-14 at 12 28 39" src="https://user-images.githubusercontent.com/82535909/163356624-0777d6be-b6e2-4d4d-8f93-40bff5220c31.png">


I hope the error leads somewhere so we can fix this, but if I can help with additional information please let me know!

**Comment by girishpanchal30** [comment] 2022-04-14 09:47
@Skystream96 Thank you for the checking, Can you please share the google sheet URL here?

**Comment by MarinescuLucia** [comment] 2022-04-16 09:29
Hi @girishpanchal30!

Sorry for the late reply! I created a couple of spreadsheets following the exact steps from the document you provided, but on a TasteWP instance the error was still occurring. These are two of the spreadsheets I used: [spreadsheet1](https://docs.google.com/spreadsheets/d/e/2PACX-1vS9bqkGi3fnVTYJJ5-a0j-hSRAXNK-r4HBwq_302iCe2yaOJGcRVNqkdm-IDie_iqBu6ZNcxPjeYsWy/pub?output=csv), [spreadsheet2](https://docs.google.com/spreadsheets/d/e/2PACX-1vRzM8IcSMVtD4j0wjRssYuXBvSEOwPREgarTC-edOP04r40IZZ4bUEiEd2XGqGNoLik6FLdCofinjA0/pub?output=csv). I've recorded a [video](https://www.loom.com/share/6e63bd2b982a4d9eb2e265bac2708e50) so you can see the behavior. However, I tested this on a Local instance as well, with the exact same spreadsheets and everything worked properly there. I didn't get any error, not even in the Console, so I thought it was appearing only on TasteWP instances because sometimes certain functionalities of Visualizer don't work as expected on TasteWP. Just to make sure, I asked Poonam to check on Local as well, to have one more opinion, but here comes the weird thing, for her, as for Matei, the error is still occurring on Local, so I guess it's not related to TasteWP.

I've used the latest version of Visualizer, WP 5.9.3, PHP 7.4.1.

**Comment by girishpanchal30** [comment] 2022-04-18 04:39
@MarinescuLucia I'll check the issue and update you here...
Thanks

**Comment by girishpanchal30** [comment] 2022-04-18 09:17
Hello @MarinescuLucia,

I have checked with my local and TasteWP instances and I can't find any issue. You can check my test instance here.

https://futureadjustment.s3-tastewp.com/wp-admin/
username: kwt_girish
password: gpkwt@123

https://docs.google.com/spreadsheets/d/e/2PACX-1vQoH7krK1Q48cBh4D9sNVgokTP70JpGqmVz_xEybcgoVxEP7jSsGn8EixDgIWYLvsNeEKkQ-NBeU_tO/pub?gid=662068267&single=true&output=csv

https://docs.google.com/spreadsheets/d/e/2PACX-1vQoH7krK1Q48cBh4D9sNVgokTP70JpGqmVz_xEybcgoVxEP7jSsGn8EixDgIWYLvsNeEKkQ-NBeU_tO/pub?gid=1411818610&single=true&output=csv

Thanks

**Comment by vytisbulkevicius** [comment] 2022-04-19 14:21
@MarinescuLucia, @Skystream96,

It works fine for me too. I also checked the URLs that Lucia provided are not correctly shared.
They look like this:
https://docs.google.com/spreadsheets/d/15hU5FDbW9JojQL3BXBo1WbUN7P8MFyrr0pl1kkq0VEw/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1-1WdNLRVKkTrxMF1f45HR0C_ySYyyS0Ff6YL2eDvDGk/edit?usp=sharing

A correctly shared file should the `output=csv` in the URL, **not** `usp=sharing`. For MPG that's not needed but for Visualizer we need to have the file shared as CSV.

Another example of a correctly shared file(has the same data as Lucia's file) - https://docs.google.com/spreadsheets/d/e/2PACX-1vQHKvB3maPsLKYf9sWHfeT0F7QskXBwQv1XdF1UjwH0fZ8iYWEelv_TokhBg9NnUGjrRp4jWIvzE_yO/pub?output=csv

Please confirm that it works for you and let's close this issue then.

Thank you for your help Girish, apologies for the confusion.

**Comment by MarinescuLucia** [comment] 2022-04-19 18:49
@vytisbulkevicius I firstly added the link for the csv version but I saw that it was downloading the file when it was clicked instead of opening the link, so I edited my reply and replaced it with the link to the actual spreadsheet where the link for the csv version can be generated. I tested it every time with the csv version of the link and it works properly for me on Local, not TasteWP, but Poonam tested this again during our 1:1 and she got the same error as Matei. However, I agree that this issue could be closed since it doesn't occur on a regular basis on all environments and taking into account that no other users reported it. Thanks!

**Closed** 2022-04-20 19:33 UTC

**Comment by Skystream96** [comment] 2022-06-17 09:10
Hello @girishpanchal30 ,

Coming back on this one as the user still reported that it doesn't work. I gave it another try and still couldn't manage to make it work. I have tried different browsers, and different versions of the plugin down to 3.6.1, and switched my local instance from ngnix to apache for a Hail Mary but still to no avail. 

I have noticed that Chrome does not throw any errors, whilst Firefox provides this one.
![Screenshot 2022-06-17 at 11 54 11](https://user-images.githubusercontent.com/82535909/174264629-28faea57-54e3-4d42-a7d4-5a5ab2157687.png)

I also created multiple instances on TasteWP and one some it works, on some it doesn't, but I couldn't find any difference between the instances as I used the same manner and settings to create all of them.

Do you think it has anything to do with fresh instances? Maybe a database reset would help in some way? I have tried using WP Reset to delete transients and even reset the whole website but that still didn't work.

This is indeed an edge case but if it already happened to 2 users (me and the user reporting the issue) I think it's best to take a final look at it just in case it spreads to multiple ones.

Do you have any more ideas? Anything would help.

Thank you!

**Comment by girishpanchal30** [comment] 2022-06-17 09:19
Hello @Skystream96,
I'll check this issue and update you here.

Thanks
