### ISSUE TITLE
FSE/Theme Compatibility in the Editor

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/visualizer#1050] opened 2023-11-14 09:23 UTC
### Description

I tried following the the Golden Path in the Visualizer onboarding, by installing it on a test instance and import a demo chart; **but it won't work in the Editor context:**

![image](https://github.com/Codeinwp/visualizer/assets/52494172/513ca886-284b-4699-af45-3707db5d8aa8)

___

after installing Neve instead of 2023 theme, the chart works in the editor.
Looking into Metabase feeback, I see mentions about this from 8th of November.

**Note:** the chart works in the front end, so the issue is visible only in the Editor.

___
### Step-by-step reproduction instructions

1. Crete a test instance with 2023 theme | WP 6.4.1 | Visualizer 3.10.4
2. Start the onboarding
3. Select the Bar Chart
4. Finish the onboarding and select to open the Draft (demo) page

### Screenshots, screen recording, code snippet or Help Scout ticket

https://github.com/Codeinwp/visualizer/assets/52494172/10745a8f-e8c0-4cb9-8c43-38e982aa59da

### Environment info

https://pastebin.com/e8YAhHNz

### Is the issue you are reporting a regression

No

**Comment by mghenciu** [comment] 2023-11-14 10:18
After doing more testing, it looks like **it happens also with the Astra theme - which is not FSE.**
So it may be not related only to FSE.
![Screenshot 2023-11-14 at 12 17 32](https://github.com/Codeinwp/visualizer/assets/52494172/22224fa5-cd58-4561-b63f-f46c981d7fd3)

**Comment by girishpanchal30** [comment] 2023-11-16 10:10
Hey @mghenciu,

I've reviewed this issue and the issue is related to `lodash` JS, I already fixed it with this PR https://github.com/Codeinwp/visualizer/pull/1048

Thanks

**Comment by irinelenache** [comment] 2023-11-17 09:35
@girishpanchal30 Tested and the issue is fixed now, thank you 🚀

**Closed** 2023-12-22 15:17 UTC
Labels: bug
