### ISSUE TITLE
Issue with Dates

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#311] opened 2018-10-22 12:40 UTC
- This issue happens when you open the sample data of Table chart.
- This issue also happens when I use the data of our charts with REST in a React component.

The date column of the chart doesn't work, and I believe it's an issue with date formatting.

More details: https://groups.google.com/forum/#!topic/google-visualization-api/-I4JoNBkh-E

It needs to be fixed for me to work on the Gutenberg block. In the JavaScript side, if I use `new Date("whatever-the-date-is")` it works just fine. If possible can we save the proper date format into custom fields I can fetch it directly in Gutenberg without redoing the entire formatting?

Discussed with @contactashish13 already.

Let me know if any other questions are there. :D

**Comment by HardeepAsrani** [comment] 2018-10-22 12:49
It happens with all charts with Date column. Even if it doesn't happen on PHP side, it's happening on React side. (maybe somewhere we're formatting the data in PHP before rendering for some charts?)

**Comment by HardeepAsrani** [comment] 2018-10-22 13:14
Here's how I was able to reproduce it: https://drive.google.com/file/d/1EPriDs4PwYegAVs9JEWhhCCO501yy8Oz/view?usp=sharing

Also shows the error it produces on React site.

**Comment by contactashish13** [comment] 2018-10-23 03:32
@HardeepAsrani as mentioned on slack I cannot reproduce this. @mileamadalin can you please include this while testing #312?

**Comment by mileamadalin** [comment] 2018-11-13 16:26
@contactashish13 I confirm this bug. This issue occurs only on FireFox and Safari.

Worked fine on Google Chrome. 

Tested with the Latest version of WP WP5

Google Chrome: -> working as expected 

![google chrome](https://user-images.githubusercontent.com/6906834/48427138-c7d86080-e770-11e8-8e46-ee04a68c28ff.png)

FireFix -> bug

![screenshot 2018-11-13 at 6 13 57 pm](https://user-images.githubusercontent.com/6906834/48427160-d3c42280-e770-11e8-8dfe-f960ad9692c7.png)

Safari -> bug

![screenshot 2018-11-13 at 6 12 07 pm](https://user-images.githubusercontent.com/6906834/48427184-e2aad500-e770-11e8-9055-d2488347eacf.png)

I was able to replicate it by using Hardeep steps.

**Comment by mileamadalin** [comment] 2018-11-21 08:15
@contactashish13 a customer reported us a similar issue. I have tested with Chrome and I was able to replicate the issue. This time the bug occurs on "Combo" chart. 

I have tried another chart and works. Please see the videos below: 

The video sent from the customer part:  https://share.vidyard.com/watch/EBevQ5SS1S6zrBwPit1vNt 
Tested by me on the customer website: https://drive.google.com/file/d/1WZY7huzH49IOKs0ZBEvFjVi8if1G4iMi/view

Tested on my local machine with Chrome -> Combo chart -> BUG
https://drive.google.com/file/d/1pt0SGqq9QyUpWuadp2OObWIiXRfdfWjG/view

Tested on my local machine -> Column -> Works

https://drive.google.com/file/d/1d9CF6xSHQZsJEHyZilhdgynmfBgG30TY/view

**Comment by contactashish13** [comment] 2018-11-22 03:38
@mileamadalin I've tried exactly what you did on Chrome and Firefox and was not able to reproduce the error with Combo chart. Are you trying with the latest version? Can you try on a public instance that we can both have access to?

**Comment by HardeepAsrani** [comment] 2018-11-22 17:20
Madalin commented with:

```
@contactashish13 Yep. I have tried with the latest version. You can check the customer webiste as I did.

Ticket link: https://secure.helpscout.net/conversation/707856590/173514?folderId=212385
```

Removed his comment as it mentioned user's pirate token which shouldn't be shared in a public repo. @mileamadalin you can send that personally on Slack, or just add a note on the ticket. 😄

**Comment by contactashish13** [comment] 2018-11-28 13:14
@mileamadalin the issue reported by Hardeep is different from the HS user even though both are similar . Please don't mix the two. You can create a new issue.

As far as the original issue is concerned. the problem is because our sample files contain invalid dates in the format `YYYY/MM` whereas they should be `YYYY/MM/DD`. Have fixed this now as part of PRs https://github.com/Codeinwp/visualizer/pull/325 and #324

**Comment by contactashish13** [comment] 2018-12-03 08:19
@mileamadalin please test this with the new version.

**Comment by mileamadalin** [comment] 2019-01-30 12:33
@contactashish13 Tested and now worked as expected. We can close it.

**Closed** 2019-01-31 11:54 UTC
Labels: bug
