### ISSUE TITLE
Duplicating a chartjs chart will create the new chart with google charts instead

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#528] opened 2019-09-13 16:21 UTC
This was discovered by user feedback

I was able to reproduce it: : https://i.imgur.com/zUn4zqU.png

131 is a duplicate of 129, to reproduce, just create a default bar chart with chartjs and duplicate it

**Comment by DanyCaissy** [comment] 2019-09-13 17:19
Note: In case this helps debugging...if you duplicate a chart (and it creates a google chart instead of a chartjs chart), then modify and save right away the duplicated chart, its title will become "Array".

**Comment by contactashish13** [comment] 2019-09-14 02:55
Closing as this is a duplicate of https://github.com/Codeinwp/visualizer/issues/514.

PS - @DanyCaissy could you check if the issue already exists before creating a new one?

**Closed by contactashish13** 2019-09-14 02:55 UTC
Labels: bug
