### ISSUE TITLE
add revision support

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#243] opened 2018-03-12 10:39 UTC
@contactashish13 I would like to introduce revision support for charts post_type. 

The intent is to solve the next issue: 

When we try to edit a chart, if we change some data and click on view editor, the data is automatically saved, despite we did not click the save button chart. The problem here if the user has a chart with some data associated and he tries different importing ( import from WP, DB ), the previous data is overwritten and there is no way to undo this

In order to solve this issue, we will need to add revision support for this chart, enable revision save only we are in edit mode and revision data to the active chart when the click Save.

**Comment by contactashish13** [comment] 2018-03-19 07:32
@selul we can't really save "into" a revision so here is what I suggest. Let me know if this works.

1. enable revisions
2. when the user modifies the chart without Saving, let current functionality remain
3. provide a Cancel button - this will undo the current revision 
4. provide a Save button - no change in functionality
5. remove the close button (x) from the window so that users can use only save or cancel

**Comment by selul** [comment] 2018-03-19 08:48
@contactashish13 in this behaviour, if the user choose cancel after he edited some data using the manual data, the chart will show the data before he would choose the edit ?

**Comment by contactashish13** [comment] 2018-03-19 08:50
@selul yes, we would undo the latest version and go back to the last revision

**Comment by contactashish13** [comment] 2018-03-20 09:14
@selul PR: https://github.com/Codeinwp/visualizer/pull/246

I wasn't able to do the following:
1. Prevent modal from closing by clicking escape or on clicking the background
2. Style the cancel button
3. Create test case (will try again)

**Comment by selul** [comment] 2018-03-20 09:15
@contactashish13 if they will click on escape or background, they will get the chart state before opening for edit?

**Comment by contactashish13** [comment] 2018-03-20 09:16
@selul no. That is why we need to disable closing of modal on clicking escape/background. The only way out of the process has to be either save or cancel button.

**Comment by selul** [comment] 2018-03-20 09:19
how about if they click on page refresh, the chart will still load the revision data?
If yes, we need to find a way to solve this, the only time when the chart data will be edited is when they will click on save. 
Maybe we can load the revision id as soon as they open for edit?

**Comment by contactashish13** [comment] 2018-03-20 13:11
@selul I've handled this at 2 ends - one while loading the library and one while editing.

**Comment by selul** [comment] 2018-03-21 14:56
@contactashish13 i dont understand your last reply ?

**Comment by contactashish13** [comment] 2018-03-22 05:22
the revisions are removed 

when the user edits the chart
OR
when the user refreshes the library

**Comment by selul** [comment] 2018-03-22 08:42
@contactashish13 please confirm if this is the behaviour: 
`When the user edits a certain chart, if he did any other action except Save, the content is not saved.`

**Comment by contactashish13** [comment] 2018-03-22 08:54
@selul as discussed in https://github.com/Codeinwp/visualizer/issues/243#issuecomment-374123282, the behavior of the chart remains the same. Data is still saved in the chart but with with revisions enabled. And the oldest revision is reinstated if either of the below conditions is true

- the user clicks cancel
- the user refreshes the page/library page
- the user edits the chart

**Comment by selul** [comment] 2018-03-22 08:58
@contactashish13 how about if he clicks save, is the previous chart id changed, or it stays the same?

**Comment by contactashish13** [comment] 2018-03-22 09:02
@selul if the user clicks save, all revisions will be discarded. Thus chart id remains unchanged.

**Comment by selul** [comment] 2018-03-26 11:05
@rohittm can you help me test this, 
Let me know what use cases you have tested and if is the case, what problems you have found.

**Comment by contactashish13** [comment] 2018-03-27 09:17
@rohittm please provide step by step details of what you tried to test here
> In all the above three cases, the changes weren't made until and unless "Save Changes" button was clicked

the problem with pro appears to be a problem with your install.

**Comment by rohittm** [comment] 2018-03-27 19:37
Steps here are:
1. I created a new chart.
2. Changed the data in csv and uploaded it.
3. Worked with these scenarios:
 > Close the browser tab.
 > Close the modal clicking on background.
 > Close the modal using cancel button.
4. In these cases, the chart data was rolled back to the last version. The data was updated to the new version only when "Save Changes" button was clicked.
In [this](https://github.com/Codeinwp/visualizer/issues/243#issuecomment-374526630) comment, you wanted this action, right?

**Comment by contactashish13** [comment] 2018-03-28 13:09
@rohittm I've tested with the same combination and found no problem. I suppose you have to give the plugin time to work - e.g. the import from another chart feature brings data from the database to the interface and then submits - so its not an instantaneous process. It may help if you test all the features using the master branches of both pro and free so that you understand how they work before testing them against specific issues. It will avoid false positives.

**Comment by selul** [comment] 2018-04-10 09:07
@contactashish13 can you fix the conflict for the revision PR. i think it should be fine after.

**Comment by selul** [comment] 2018-04-10 09:41
@contactashish13 one more thing, can we add unit tests for this particular feature ?

**Comment by contactashish13** [comment] 2018-04-12 05:38
@selul PR: https://github.com/Codeinwp/visualizer/pull/250

**Comment by rodica-andronache** [comment] 2018-04-19 09:44
@contactashish13 I tested a bit, and I'm not sure if it's ok. I created this chart https://prnt.sc/j7a3l5, clicked Edit, View Editor, updated one of the values, clicked Show Chart and clicked outside the window (without save or cancel ) and the value seems to be saved https://prnt.sc/j7a4jp
@rohittm maybe you can test too? 
👍

**Comment by contactashish13** [comment] 2018-04-20 05:24
@rodica-andronache The chart will be saved. The old behavior remains the same. But if you click Edit again or if you refresh the library, the new revision will be discarded and the old version of the chart will show.

**Comment by rohittm** [comment] 2018-04-24 20:41
@contactashish13 

The steps I did to reproduce this:

1. Fresh install of WP on Local by Flywheel
2. Installed and activated [issue-243](https://github.com/contactashish13/visualizer/tree/issue-243) branch of Visualizer.
3. Created a line chart, with a new sample data (.csv)
4. Clicked on 'Save Chart', Chart is created: 

![screen shot 2018-04-25 at 01 51 30](https://user-images.githubusercontent.com/3204558/39212062-358b95d8-482b-11e8-956c-f1f5a911e0c2.png)

5. Now, I edit chart, import a new sample data, Here are the three scenarios I worked on.
    i. Clicking on popup background and the popup is closed and the old version of chart is not retained ❌
    Here's the video for same: https://drive.google.com/file/d/1ymfGKbPPIlOsTNY8MY6za-DJvvhoEkFZ/view?usp=sharing

    ii. Clicking on 'Cancel' button, but the new chart is saved rather than the old one. ❌
    Here's the video for same: https://drive.google.com/file/d/11RECg7vKaOtxfejZFqvX7fcPnueL4rL6/view?usp=sharing

    iii. Refreshing the page. The new chart is saved instead of the old one. ❌
    Here's the video for same: https://drive.google.com/file/d/1zqIroZ9h3rvxzASQMXMhbDx_9sis0H05/view?usp=sharing

That's how I tested. Let me know if anything is not understood.

**Comment by rohittm** [comment] 2018-04-25 10:39
@contactashish13 
[revision.zip](https://github.com/Codeinwp/visualizer/files/1946606/revision.zip)

All files are named revision_test_<1, 2, or, 3> 

1, 2, and, 3 are the scenarios from above issue (5.i, 5.ii, and, 5.iii)

**Comment by contactashish13** [comment] 2018-04-25 18:43
@rohittm can you test the PR again? The scenarios I've tested assume I create a new chart every time before operating on it. This prevents any "dirty" data. Please try to follow the same methodology. Once they succeed, you can try random scenarios as well.

Here are the scenarios assuming a clean chart in the library:

1. Edit, import a new chart, cancel - old version shows
2. Edit, import a new chart, click pop up background or refresh page - old version shows
3. Edit, import a new chart, click pop up background, do not refresh page, click edit again - old version shows
4. Edit, import a new chart, save chart - new version shows

**Comment by rohittm** [comment] 2018-05-11 16:59
@contactashish13 

1. Works fine.
2. Works fine.
3. Works fine.
4. Works fine.

**Comment by rodica-andronache** [comment] 2018-05-22 11:04
@contactashish13 @rohittm for me, the problem is like this:
Create a new chart with import data from file.  -> Use the shortcode on a page.
Edit that chart. Add an updated file for import data from file. 
Click outside the popup https://prnt.sc/jl2ysf instead of clicking Cancel or Save Chart.
In the Visualizer dashboard, indeed the chart is not updated, but if you go on the page where you've used the shortcode, you will see the updated chart.

Could you please check this case?

**Comment by contactashish13** [comment] 2018-05-24 09:54
@rodica-andronache have fixed this case as well as another case when the chart is edited from the front-end. I have a feeling this will be a problem with scheduled charts as well. I've added support but I can't test it this till these changes are merged with #255.

PR: https://github.com/Codeinwp/visualizer-pro/pull/108

**Comment by rodica-andronache** [comment] 2018-05-25 09:21
@contactashish13 that problem seems to be fixed. thanks 👍 
I merged it on dev, you can see if there are other problems too.

@rohittm would you please have another look on this? https://github.com/Codeinwp/visualizer/pull/249 to see if there are any other problems?

**Comment by contactashish13** [comment] 2018-05-26 07:05
@rodica-andronache ran into #265 but everything else looks good.

**Closed** 2018-06-27 13:34 UTC
Labels: enhancement
