### ISSUE TITLE
selecting the line chart is not working on instawp

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#940] opened 2022-09-23 07:26 UTC
### Description:
Hi there, 

I wanted to test something related to visualizer and I could not create the default line chart, i.e clicking the next btn does not work https://vertis.d.pr/5PADuI

Site details:
https://yatowi.s.themeisle.com/wp-admin
Username yatowi
Password D8cemkTs

Seems like thee is an error report: 
```
[Fri Sep 23 07:24:48.850917 2022] [proxy_fcgi:error] [pid 1247121:tid 140130882873088] [client 82.76.228.197:0] AH01071: Got error ' be resource, null given in /home/senatoyecunojaxa/webapps/yatowi/wp-content/plugins/visualizer/classes/Visualizer/Module.php on line 285PHP message: PHP Warning: Invalid argument supplied for foreach() in /home/senatoyecunojaxa/webapps/yatowi/wp-content/plugins/visualizer/classes/Visualizer/Module.php on line 293PHP message: PHP Warning: fgetcsv() expects parameter 1 to be resource, null given in /home/senatoyecunojaxa/webapps/yatowi/wp-content/plugins/visualizer/classes/Visualizer/Module.php on line 285P
```

**Comment by girishpanchal30** [comment] 2022-09-23 09:16
@selul I have fixed the temporary file creation issue on the test instance. Please check and do let me know if you have any issues.

Thanks

**Comment by irinelenache** [comment] 2022-09-23 11:33
@girishpanchal30 Tested and the issue is fixed now, thank you 👍

**Closed** 2022-10-12 17:03 UTC
Labels: bug
