### ISSUE TITLE
add support for annotation and other roles

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#214] opened 2017-10-26 07:48 UTC
https://secure.helpscout.net/conversation/455466468/146245/?folderId=212388

**Comment by contactashish13** [comment] 2019-10-29 16:41
PR https://github.com/Codeinwp/visualizer/pull/560 adds support for multiple `roles` as defined in https://developers.google.com/chart/interactive/docs/roles#what-roles-are-available

This option will be available under each series as below
![image](https://user-images.githubusercontent.com/12953439/67788544-8d0e2c00-fa98-11e9-8877-357e40faab71.png)

The intent is to allow the user to upload any CSV/data and **afterwards** provide the role of the series without changing any process. So, our default line chart can become 

![image](https://user-images.githubusercontent.com/12953439/67788685-cba3e680-fa98-11e9-9e45-c2f0f4abbf36.png)

or

![image](https://user-images.githubusercontent.com/12953439/67788780-eece9600-fa98-11e9-8f9e-2c34097b7699.png)

@SilviuDinu can you please try this out? cc @DanyCaissy

**Comment by SilviuDinu** [comment] 2019-11-07 15:00
@contactashish13 

tested on both local and jurassic-ninja

### Annotations
I think there is a weird behavior on **bar / column charts** with annotations. Or at least I don't understand exactly how it should work. 
1. For instance, I tested on a bar chart and every time I select the annotations role for a series, that particular series **vanishes** from the **chart and legend,** its color is inherited by the next series and the annotation is placed wrongly.
2. I chose the **annotations** role for all the series and they all vanished. 
3. If you try to revert to Default (data) role, nothing happens. The only way to "**reset**" the chart that I could find was to **manually** change a value in the **Live editor.**

I would expect it like this -> http://prntscr.com/pts4eu

I know that the role defines how it should behave. So if I select annotation, the graph will turn into values and it will be placed on the axis accordingly, but I find the bar chart behavior a bit unexpected from my pov. Maybe I'm wrong.

Video for the behaviour presented above -> [VIDEO URL](https://share.vidyard.com/watch/4kv54989ekXaU2hAJdNoZ6?)

**The line chart** seems to behave correctly like expected, but it still has the 3rd issue from above:

> 3. If you try to revert to Default (data) role, nothing happens. The only way to "**reset**" the chart that I could find was to **manually** change a value in the **Live editor.**

### All the other roles apart from annotation
**Bar / Column Charts** - If you add **any** role (except annotation) for one graph (series), that particular one vanishes from the chart and legend. Not sure if it's the correct behavior or not. But I still find it weird.

**Comment by contactashish13** [comment] 2019-11-11 08:15
@SilviuDinu as explained and understood by you, selecting any role will take the series out of the chart. Therefore the below should no longer be a cause for confusion. Could you please edit your comment accordingly?

> Bar / Column Charts - If you add any role (except annotation) for one graph (series), that particular one vanishes from the chart and legend. Not sure if it's the correct behavior or not. But I still find it weird.

I have fixed the issue two issues you have found. 

In the document, you can use the attached CSV file as an example of how to provide annotations. Please note that the annotation column needs to be immediately after the series it provides the values for.

[line.zip](https://github.com/Codeinwp/visualizer/files/3830028/line.zip)

**Comment by contactashish13** [comment] 2019-11-11 08:19
@DanyCaissy can you also test this please?

**Comment by DanyCaissy** [comment] 2019-11-13 02:00
The annotation setting is reset when data is changed, is that intended?: 

![2019-11-12_19-41-39](https://user-images.githubusercontent.com/5183243/68722789-9614f800-0584-11ea-85ef-f161e9668824.gif)

Additionally, it seems every two times you load a chart (more or less), it loads infinitely, here's a gif to show it:


![2019-11-12_20-55-08](https://user-images.githubusercontent.com/5183243/68726252-e002db80-058e-11ea-9a82-19b3a2020132.gif)

And the instance to reproduce that:
https://fun-eels.jurassic.ninja 

WP user: demo WP/SSH password: jrVBmwlZqyMT

I  am using the PR here + the latest visualizer pro from https://store.themeisle.com/

I haven't encountered other issues so far.

**Comment by contactashish13** [comment] 2019-11-13 05:49
@DanyCaissy what you are trying to do in step 1 is something that has always been a problem with the UX. Just like when you add a new series, it does not reflect in the settings unless you save the chart. Similarly, any changes in the settings is temporary till the chart is not saved. Our users have got used to this idiosyncrasy and till the complete overhaul, we should too :) The correct workflow would be - change the role, save the chat, edit the chart, edit the data, save the chart.

For step 2, thanks for pointing this out. This would have been a critical issue had it slipped through. I've fixed it as part of the same PR. Could you please test again?

**Comment by DanyCaissy** [comment] 2019-11-13 17:22
@contactashish13 

1- Yeah I do remember it being an issue previously, just wanted to make sure.

2- That is fixed

**Comment by contactashish13** [comment] 2019-12-22 05:33
@SilviuDinu can you add an example for https://wordpress.org/support/topic/charts-how-to-show-string-on-only-on-series-point-hover/ to the document?

**Comment by contactashish13** [comment] 2020-01-27 08:45
@DanyCaissy is there a reason this has been kept for the next release instead of the current release?

**Comment by rodica-andronache** [comment] 2020-02-06 13:18
@contactashish13 I've tried creating an example to add here https://docs.themeisle.com/article/1160-roles-for-series-visualizer for the tooltip, and even though I managed to do that, when I'm building the chart ( before choosing the tooltip role for one of the columns ) and when inserting the chart in a post I get this error "All series on a given axis must be of the same data type".
I know the annotations don't work in the editor, but I was thinking that maybe there's something to do to at least see the normal chart. Is there something I'm missing?

https://www.loom.com/share/bd4f35bad7474c9aad28bf83f8caae57

**Comment by rodica-andronache** [comment] 2020-02-06 14:16
another thing which doesn't work for me and I'm not sure if I'm testing properly or not.
I tried testing the Style role, and after I created the chart, and try to edit it, the data does not update in the visualizer editor, until I save the chart due to an error I get in the console.

https://www.loom.com/share/9bb0bc94436d45719fc2fee74a569cf3

**Comment by rodica-andronache** [comment] 2020-02-06 14:35
for the **scope** role, I've created a chart like this using `true` and `false` in the `Text editor`
![download (7)](https://user-images.githubusercontent.com/3266155/73946248-4719fd00-48fe-11ea-9159-5abe15aa8878.png)
and is working well
![download (8)](https://user-images.githubusercontent.com/3266155/73946285-5731dc80-48fe-11ea-8ac0-66efb39a3942.png)

But if I go and edit the chart in the Simple editor, the `false` items have disappeared.
![download (9)](https://user-images.githubusercontent.com/3266155/73946380-82b4c700-48fe-11ea-835c-fbdfb8af75c3.png)
and if I go ahead and add `0` there, the out of scope points don't show up as before.
![download (10)](https://user-images.githubusercontent.com/3266155/73946466-a415b300-48fe-11ea-9ff2-582c0b3660d5.png)

**Comment by rodica-andronache** [comment] 2020-02-06 15:22
Not a big deal, but I think if possible, it would make sense for the `annotation role` to don't display that little line for points that don't have a value.
![download (11)](https://user-images.githubusercontent.com/3266155/73950705-0b366600-4905-11ea-826a-5276ec0d3afc.png)

Like in their example
![download (12)](https://user-images.githubusercontent.com/3266155/73950817-3faa2200-4905-11ea-9874-5e803c2b98c3.png)

**Comment by rodica-andronache** [comment] 2020-02-06 16:02
@contactashish13 I've finished https://docs.themeisle.com/article/1160-roles-for-series-visualizer. To conclude what I've tested regarding this, all annotations roles work well, it's just that ( at least I don't know how to do it correctly ) the process to get it done has some issues ( the ones I've mentioned ).
The biggest one is the first one I've mentioned. If you try to first enter the manual data, and then go ahead and add the column as an annotation, you get this error and the chart is not visible. Plus, there are some `""` appearing in the visualizer editor. ( these appear even after the chart is created and everything is ok, and you try to edit the chart )
![Screenshot (6)](https://user-images.githubusercontent.com/3266155/73954585-af6edb80-490a-11ea-8a43-eda15adef419.png)

**Comment by contactashish13** [comment] 2020-02-07 13:37
@rodica-andronache 

for https://github.com/Codeinwp/visualizer/issues/214#issuecomment-582901584 - can't do anything as that's how the API behaves. It may help to list this behavior in the document.

for https://github.com/Codeinwp/visualizer/issues/214#issuecomment-582925111 - if you use double quotes it works properly. Single quotes will not work.

https://github.com/Codeinwp/visualizer/issues/214#issuecomment-582933665 and https://github.com/Codeinwp/visualizer/issues/214#issuecomment-582955866 have been fixed in the PR https://github.com/Codeinwp/visualizer/pull/634. It also fixes the double quotes that show up after editing the data.

**Comment by rodica-andronache** [comment] 2020-02-07 14:04
@contactashish13 ok, if there's nothing that can be done for that, I'll try to explain it in the doc.
The other things work well now 👍 
I saw another small thing while testing this again. 
For a chart I have with the **style** role, if I try to edit it twice using the **Simple** editor, the second time, all the values disappear from the chart.
https://www.loom.com/share/68e648030248474b91c07bd00225024b

**Comment by contactashish13** [comment] 2020-02-10 13:04
@rodica-andronache I've fixed the issue you have reported (https://github.com/Codeinwp/visualizer/pull/635). These changes make sure that in the **text editor** single and double quotes are treated at par (and either get removed if they are not required or get converted to double quotes). In the **simple editor** you don't have to provide any quotes as each cell is a value in the CSV and internally gets enclosed with quotes. Effectively, what you provide in one editor should also be editable in the other editors. Example: if you enclose a value with a quote in the text editor, the quote will vanish in the simple/excel editor and if you provide a value that has a comma in the simple/excel editor, it will show up with a quote in the text editor.

**Comment by rodica-andronache** [comment] 2020-02-10 14:14
@contactashish13 that's working well now, but how about when you need an apostrophe in the name? Is this possible?

If I add it in the `Text editor`, it gets transformed in a `double quote`
![download (2)](https://user-images.githubusercontent.com/3266155/74156948-0da80100-4c20-11ea-9975-3c7001255e6e.png)
![download (3)](https://user-images.githubusercontent.com/3266155/74156955-139de200-4c20-11ea-9abb-ffa06c820174.png)

and in the `Simple editor`, it gets transformed into `\'`
![Screenshot (2)](https://user-images.githubusercontent.com/3266155/74157052-447e1700-4c20-11ea-8360-510fe5ff79f8.png)
![Screenshot (3)](https://user-images.githubusercontent.com/3266155/74157074-5364c980-4c20-11ea-81a7-871e797d7831.png)

**Comment by contactashish13** [comment] 2020-02-11 08:59
@rodica-andronache can you create a new issue for this that we can tackle as part of the next release?

**Comment by rodica-andronache** [comment] 2020-02-11 09:46
ok, I've moved it here https://github.com/Codeinwp/visualizer/issues/637

**Closed** 2020-02-14 14:12 UTC
Labels: enhancement
