### ISSUE TITLE
auto_detect_line_endings is deprecated

### ISSUE THREAD

**Issue by jrandyanderson** [Codeinwp/visualizer#1053] opened 2023-11-16 16:58 UTC
### Description

Upon upgrading to PHP 8.1 I am getting this deprecation notice:

`[11-Nov-2023 06:10:08 UTC] PHP Deprecated: auto_detect_line_endings is deprecated in /dom43717/wp-content/plugins/visualizer/classes/Visualizer/Source/Csv.php on line 119`

### Step-by-step reproduction instructions

1. Go to WP Admin side of site
2. Go to Visualizer admin page

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment] 2023-11-17 11:24
Hey @vytisbulkevicius,

I've removed the deprecated functions from a plugin, and I believe they are not required now.
Ref: https://php.watch/versions/8.1/auto_detect_line_endings-ini-deprecated

Thanks

**Comment by irinelenache** [comment] 2023-11-20 09:15
@girishpanchal30 Tested and the issue is fixed by the PR 👍

**Closed** 2023-12-22 15:20 UTC
Labels: bug, released
