### ISSUE TITLE
renderChart() method causing exponential page growth when displaying multiple charts 

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/visualizer#857] opened 2021-11-01 07:57 UTC
### Description:
One of our users discovered a method that is significantly stressing server resources once a page contains multiple charts. Based on their report it seems like the more charts you publish on one page, the more resources will be consumed and timeouts will appear.

This is more of a performance enhancement request rather than a bug but I think it's worth looking through it. 

Here is the link to the ticket in question where the patch applied by the user is alongside a more detailed description of the issue: https://secure.helpscout.net/conversation/1680591815/297607?folderId=212390

**Comment by vytisbulkevicius** [comment] 2021-11-01 08:03
@Skystream96,

This is related to - https://github.com/Codeinwp/visualizer/issues/851

**Comment by Skystream96** [comment] 2021-11-01 12:41
> @Skystream96,
> 
> This is related to - #851

@vytisbulkevicius Thank you for pointing this out and for connecting them.

**Comment by cristian-ungureanu** [comment] 2021-11-16 07:51
Closing  this issue as it's a duplicate of https://github.com/Codeinwp/visualizer/issues/851

**Closed by cristian-ungureanu** 2021-11-16 07:51 UTC
Labels: enhancement, investigation
