### ISSUE TITLE
Clicking Copy shows the Copied message multiple times

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#676] opened 2020-04-03 00:15 UTC
Issues to fix:

- When clicking copy, the alert appears twice, instead of once
- Clicking copy creates a # in the URL and moves the page up, it also shouldn't do so.
- The "copied!" messages should be reworded to "The data has been copied to your clipboard. hit Ctrl-V in your spreadsheet editor to paste the data" to clarify the action to the user.

Current behaviour on 5.4 with plugins on development:

![2020-04-02_20-14-13](https://user-images.githubusercontent.com/5183243/78311353-99eaec00-751e-11ea-8df5-7a5cdbe8530d.gif)

**Comment by DanyCaissy** [comment] 2020-05-04 01:41
I've retested the "double copied message" issue and it doesn't always happen. I've identified a scenario where it happens, it seems to happen if there is a table as well as a non-table chart.

To reproduce:

[double-copy.zip](https://github.com/Codeinwp/visualizer/files/4572481/double-copy.zip)

**Comment by contactashish13** [comment] 2020-05-06 13:41
this is related to the problem explained in https://github.com/Codeinwp/visualizer/issues/591 and #600 as explained in https://github.com/Codeinwp/visualizer/issues/600#issuecomment-565421196. 

I've marked it as critical as this will have the same UX repercussions as #591 and will need to be tested equally extensively.

PR https://github.com/Codeinwp/visualizer/pull/692

**Comment by DanyCaissy** [comment] 2020-05-07 22:16
@contactashish13 I couldn't reproduce the issue anymore (I had to clear cache first).

Please also reword the message as above.

Thanks

**Comment by rodica-andronache** [comment] 2020-05-13 13:41
@DanyCaissy this part of the issue is still happening for me. Is that ok?
"Clicking copy creates a # in the URL and moves the page up, it also shouldn't do so."

Otherwise, it's working well for me

**Comment by DanyCaissy** [comment] 2020-05-14 04:53
Yes the # should be fixed as well.

**Comment by contactashish13** [comment] 2020-05-14 10:23
@rodica-andronache addressed this as well.

Because this issue is related to https://github.com/Codeinwp/visualizer/issues/689, this may need to be extensively tested.

**Closed** 2020-06-16 10:52 UTC
Labels: critical, enhancement
