### ISSUE TITLE
Visualizer 3.9.2 Import CSV data from URL broken

### ISSUE THREAD

**Issue by digser** [Codeinwp/visualizer#970] opened 2022-12-23 16:52 UTC
### Description:
When trying to import data in CSV format into a Visualizer table either from a file or URL the whirring wheel is shown into perpetuity.
Rolling back to 3.9.1 fixes the fault.  I have rolled versions forward and back three times with the same results.

### How to reproduce:

1.Create a new table
2.Try to import from a CSV using the tabular.csv example
3.

### Technical info
* WordPress version: 6.1.1
* Plugin version: 3.9.2

**Comment by girishpanchal30** [comment] 2022-12-26 05:17
I've reviewed this and I can't replicate this issue. Can you please share more details?

Screencast: https://www.loom.com/share/a3319d03960241709c756a4709f79090

Thanks

**Comment by MarinescuLucia** [comment] 2022-12-28 19:26
@girishpanchal30 This occurs when you go back to edit a chart, after it was previously created. It doesn't happen the first time when you create the chart. I'm able to replicate the issue - [screencast](https://vertis.d.pr/v/guPOw3).

Reported [here](https://wordpress.org/support/topic/cant-save-or-change-map-now-blank/).

**Comment by girishpanchal30** [comment] 2022-12-29 12:47
@MarinescuLucia,

Thanks for the explanation! Now the issue is fixed in this PR https://github.com/Codeinwp/visualizer/pull/971, please check with the build zip

Thanks

**Comment by MarinescuLucia** [comment] 2022-12-29 12:58
@girishpanchal30 Tested the PR and the chart is displayed properly now. Thanks!

**Closed** 2023-01-05 22:44 UTC
Labels: bug
