### ISSUE TITLE
UX Changes to chart settings 

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#655] opened 2020-02-27 11:07 UTC
**1) Moving to basic/advanced tab system**

https://i.imgur.com/Fdcvp9z.png

**2) Moving permissions to advanced settings**

This is mostly to conform easier to 2), if there are technical issues with this, we could instead make it its own, third tab

Using tabs will make it easier for users to go back and forth, and understand where they are.

**3) Enlarge the sidebar**

I would increase it to about 350px (from 299), the default is a little thin, and it is the focus point of the user.

**4) Bottom section**

At this point, only 'docs' will be left. My goal here for the future would be to add contextual documentation. So for example, someone on a pie chart would see multiple articles, ex: "How to create a basic pie charts", "How to add a legend" etc.

That documentation is not yet ready for all charts, but we could do the design changes to make this more a 'list' of articles. We wouldn't have more than 2-3 for each chart.

**5) Front-end subsection**

On the front-end subsection, remove the "actions" fieldset, there is no need for a fieldset since there is only one for this subsection.

Right now, two clicks are needed to get to the data, as per the gif included.

**6) Duplicate show chart buttons on free editors**

On the free editors, the show chart buttons are duplicated: https://i.imgur.com/LGdpHtm.png

We should remove the one on the left, and ensure the one within the sidebar applies the changes. 

**7) Import and Save Schedule buttons**

Rodica: For me, the two buttons Import and Save schedule are confusing. From what I understand, clicking on either one of them does the same thing, the content is imported right away, and the schedule is saved.
If I'm not missing anything, maybe just a button should be used?

https://user-images.githubusercontent.com/3266155/72337706-aef87180-36cb-11ea-8300-e731c399c0d1.png

**Comment by contactashish13** [comment] 2020-02-28 14:06
PR https://github.com/Codeinwp/visualizer/pull/657 and https://github.com/Codeinwp/visualizer-pro/pull/253

**Please note that the Cypress job in the pro build will fail till free is released. But pro can be released even with this test failing.** 

It would be prudent to test new free/old pro and new free/new pro. old free/new pro will not be supported in how the permissions are saved.

- Have created 3 tabs - one for Docs as well. 
- I'm opening the front end subsection by default instead of removing the subsection (it looks a bit ugly otherwise with the checkboxes splayed)
- Duplicate show chart buttons on free editors - already addressed in the previous release
- Import and Save Schedule buttons - the save schedule button **only** updates the saved schedule; it does not import the chart

**Comment by DanyCaissy** [comment] 2020-02-29 07:05
This is looking good. The "articles containing X" is a great idea.

The only thing I'd fix is this:

- When there is only one possible tab, please ensure it is open by default, ex: 
![2020-02-29_14-30-14](https://user-images.githubusercontent.com/5183243/75602430-0cbc0e00-5b00-11ea-8453-58ee9d90cd82.gif)

This happens in a couple other places, like general settings of a table chart.

--------------

Otherwise, I've tested new/new and new/old and it worked fine for me, I didn't come across any bugs.

**Comment by contactashish13** [comment] 2020-03-02 09:09
@DanyCaissy Have added a few more links to docs. Can you review what else to add while Rodica tests this?

**Comment by rodica-andronache** [comment] 2020-03-02 10:30
From what I've tested, everything's working well. 
The only thing that I still have doubts about is about the Import and Save Schedule buttons.
You've mentioned that the save schedule button only updates the saved schedule; it does not import the chart.
But from what I've seen, no matter if I click on Import or on Save Schedule, the chart gets imported, as you can see in the video. Let me know if I'm missing anything.
I also get a notice `Warning: Invalid argument supplied for foreach() in /Users/rodica/Local Sites/wp3/app/public/wp-content/plugins/visualizer/classes/Visualizer/Module.php on line 710`

I've tested with this file: http://rodicaelena.com/wp-content/uploads/2020/01/test-csv-line.csv
https://www.loom.com/share/d4a3ccd2bd444cd8865c6ffbbafc2922

**Comment by contactashish13** [comment] 2020-03-03 04:28
@rodica-andronache you are right. Looks like over a period of time, both buttons have ended up doing the same thing. I've combined them now. For free, only Import will show and for pro it will become Import & Save Schedule

**Comment by rodica-andronache** [comment] 2020-03-03 10:05
@contactashish13 that works well now. 
I still get that notice though `Warning: Invalid argument supplied for foreach() in /Users/rodica/Local Sites/wp3/app/public/wp-content/plugins/visualizer/classes/Visualizer/Module.php on line 710.` I've tested with the current version of Visualizer, and I didn't get it, so it must be something related to the new changes

**Comment by contactashish13** [comment] 2020-03-03 12:44
@rodica-andronache does it happen with a particular chart type/library/source? I can't seem to reproduce it.

**Comment by contactashish13** [comment] 2020-03-05 06:04
Added commits to address #509

**Comment by DanyCaissy** [comment] 2020-04-02 23:47
> @contactashish13
> 
> This is looking good. The "articles containing X" is a great idea.
> 
> The only thing I'd fix is this:
> 
> * When there is only one possible tab, please ensure it is open by default, ex:
>   ![2020-02-29_14-30-14](https://user-images.githubusercontent.com/5183243/75602430-0cbc0e00-5b00-11ea-8453-58ee9d90cd82.gif)
> 
> This happens in a couple other places, like general settings of a table chart.
> 
> Otherwise, I've tested new/new and new/old and it worked fine for me, I didn't come across any bugs.

@contactashish13 Have you addressed this comment? I haven't seen the change for that yet.

Otherwise, is there anything else you need feedback on for this ticket?

**Comment by contactashish13** [comment] 2020-04-09 13:33
@DanyCaissy have incorporated your suggestions. You can pass this on to QA if everything else is fine.

**Comment by DanyCaissy** [comment] 2020-04-11 04:15
@rodica-andronache This is ready for QA now.

**Closed** 2020-05-04 13:08 UTC
Labels: UX/UI
